In [6]:
import requests

url = "https://mashvisor-api.p.rapidapi.com/trends/summary/IL/Chicago"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

chicago = requests.request("GET", url, headers=headers)

In [8]:
chicago.text

'{"status":"success","content":{"active_neighborhoods":227,"investment_properties":4124,"airbnb_listings":1811,"traditional_listings":126,"avg_property_price":464208.0646,"avg_price_per_sqft":266.40488758,"avg_days_on_market":70.0049,"avg_occupancy":43.3189,"avg_nightly_price":188.8505,"avg_airbnb_ROI":-0.35123224573953915,"avg_airbnb_rental":2149.485022325471,"avg_traditional_ROI":1.058542109422648,"avg_traditional_rental":2134.178399636274}}'

In [12]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/CA/Los Angeles"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

los_angeles = requests.request("GET", url, headers=headers)

In [13]:
los_angeles.text

'{"status":"success","content":{"active_neighborhoods":96,"investment_properties":3883,"airbnb_listings":4988,"traditional_listings":743,"avg_property_price":1078305.77,"avg_price_per_sqft":611.89008056,"avg_days_on_market":82.0972,"avg_occupancy":63.1999,"avg_nightly_price":176.2772,"avg_airbnb_ROI":1.3174891869693832,"avg_airbnb_rental":3944.3251536986286,"avg_traditional_ROI":1.5215307901194295,"avg_traditional_rental":3857.146496187178}}'

In [14]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/NY/New York"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

new_york = requests.request("GET", url, headers=headers)

In [15]:
new_york.text

'{"status":"success","content":{"active_neighborhoods":266,"investment_properties":6252,"airbnb_listings":5722,"traditional_listings":627,"avg_property_price":1107549.5505,"avg_price_per_sqft":680.88786487,"avg_days_on_market":181.5501,"avg_occupancy":55.7123,"avg_nightly_price":164.4086,"avg_airbnb_ROI":0.0662815518467878,"avg_airbnb_rental":2577.5608684471963,"avg_traditional_ROI":0.8346552080167482,"avg_traditional_rental":2845.5438958669138}}'

In [16]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/TX/Houston"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

houston = requests.request("GET", url, headers=headers)

In [17]:
houston.text

'{"status":"success","content":{"active_neighborhoods":88,"investment_properties":1295,"airbnb_listings":2007,"traditional_listings":34,"avg_property_price":429911.5634,"avg_price_per_sqft":179.37110774,"avg_days_on_market":82.4813,"avg_occupancy":47.6564,"avg_nightly_price":105.0086,"avg_airbnb_ROI":1.0613995185149054,"avg_airbnb_rental":2115.9481401332237,"avg_traditional_ROI":1.8115951317995551,"avg_traditional_rental":1988.954066091073}}'

In [18]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/PA/Philadelphia"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

philly = requests.request("GET", url, headers=headers)

In [19]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/AZ/Phoenix"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

phoenix = requests.request("GET", url, headers=headers)

In [20]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/TX/San Antonio"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

san_antonio = requests.request("GET", url, headers=headers)

In [21]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/CA/San Diego"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

san_diego = requests.request("GET", url, headers=headers)

In [22]:
san_diego.text

'{"status":"success","content":{"active_neighborhoods":122,"investment_properties":1388,"airbnb_listings":2549,"traditional_listings":59,"avg_property_price":809468.286,"avg_price_per_sqft":518.51021318,"avg_days_on_market":53.6736,"avg_occupancy":55.9832,"avg_nightly_price":190.8563,"avg_airbnb_ROI":1.7116170966983064,"avg_airbnb_rental":3235.5384326310714,"avg_traditional_ROI":1.863602997193649,"avg_traditional_rental":3187.164404331827}}'

In [23]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/TX/Dallas"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

dallas = requests.request("GET", url, headers=headers)

In [24]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/CA/San Jose"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

san_jose = requests.request("GET", url, headers=headers)

In [25]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/IN/Indianapolis"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

indy = requests.request("GET", url, headers=headers)

In [26]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/FL/Jacksonville"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

jacksonville = requests.request("GET", url, headers=headers)

In [27]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/CA/San Francisco"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

san_fran = requests.request("GET", url, headers=headers)

In [28]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/TX/Austin"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

austin = requests.request("GET", url, headers=headers)

In [29]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/OH/Columbus"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

columbus = requests.request("GET", url, headers=headers)

In [30]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/TX/Fort Worth"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

fort_worth = requests.request("GET", url, headers=headers)

In [31]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/KY/Louisville"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

louisville = requests.request("GET", url, headers=headers)

In [33]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/NC/Charlotte"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

charlotte = requests.request("GET", url, headers=headers)

In [34]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/MI/Detroit"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

detroit = requests.request("GET", url, headers=headers)

In [35]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/TX/El Paso"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

el_paso = requests.request("GET", url, headers=headers)

In [68]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/TN/Memphis"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

memphis = requests.request("GET", url, headers=headers)

In [36]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/TN/Nashville"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

nashville = requests.request("GET", url, headers=headers)

In [37]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/MD/Baltimore"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

baltimore = requests.request("GET", url, headers=headers)

In [38]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/WA/Seattle"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

seattle = requests.request("GET", url, headers=headers)

In [39]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/MA/Boston"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

boston = requests.request("GET", url, headers=headers)

In [40]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/DC/washington"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

washington = requests.request("GET", url, headers=headers)

In [98]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/CO/Denver"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

denver = requests.request("GET", url, headers=headers)

In [43]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/WI/Milwaukee"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

milwaukee = requests.request("GET", url, headers=headers)

In [44]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/OR/Portland"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

portland = requests.request("GET", url, headers=headers)

In [45]:
url = "https://mashvisor-api.p.rapidapi.com/trends/summary/NV/Las Vegas"

headers = {
    'x-rapidapi-host': "mashvisor-api.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

las_vegas = requests.request("GET", url, headers=headers)

In [73]:
portland.text

'{"message":"500, Internal server error"}'

In [100]:
denver.text

'{"status":"success","content":{"active_neighborhoods":78,"investment_properties":142,"airbnb_listings":1358,"traditional_listings":4,"avg_property_price":513525.0915,"avg_price_per_sqft":349.51583433,"avg_days_on_market":36.29,"avg_occupancy":63.384,"avg_nightly_price":163.4523,"avg_airbnb_ROI":1.9295444587644721,"avg_airbnb_rental":2637.8674000331334,"avg_traditional_ROI":1.804805190597569,"avg_traditional_rental":1990.1760563380283}}'

In [101]:
import pandas as pd
import json

In [102]:
# function that makes the json readable, and extracts the values and returns them

def extractData(city):
    city_json = city.json()
    
    active_neighborhoods = city_json['content']['active_neighborhoods']
    investment_properties = city_json['content']['investment_properties']
    airbnb_listings = city_json['content']['airbnb_listings']
    traditional_listings = city_json['content']['traditional_listings']
    avg_property_price = city_json['content']['avg_property_price']
    avg_price_per_sqft = city_json['content']['avg_price_per_sqft']
    avg_days_on_market = city_json['content']['avg_days_on_market']
    avg_occupancy = city_json['content']['avg_occupancy']
    avg_nightly_price = city_json['content']['avg_nightly_price']
    avg_airbnb_ROI = city_json['content']['avg_airbnb_ROI']
    avg_airbnb_rental = city_json['content']['avg_airbnb_rental']
    avg_traditional_ROI = city_json['content']['avg_traditional_ROI']
    avg_traditional_rental = city_json['content']['avg_traditional_rental']
    
    return active_neighborhoods,investment_properties, airbnb_listings, traditional_listings, avg_property_price, avg_price_per_sqft, avg_days_on_market, avg_occupancy, avg_nightly_price, avg_airbnb_ROI, avg_airbnb_rental, avg_traditional_ROI, avg_traditional_rental

In [103]:
#calling the function and saving the values, to be used to make a data frame later

york = extractData(new_york)
la = extractData(los_angeles)
houst = extractData(houston)
phil = extractData(philly)
phoe = extractData(phoenix)
san = extractData(san_antonio)
sanD = extractData(san_diego)
dal = extractData(dallas)
sanJ = extractData(san_jose)
ind = extractData(indy)
jack = extractData(jacksonville)
sanF = extractData(san_fran)
aust = extractData(austin)
col = extractData(columbus)
fort = extractData(fort_worth)
lou = extractData(louisville)
char = extractData(charlotte)
det = extractData(detroit)
el = extractData(el_paso)
mem = extractData(memphis)
nash = extractData(nashville)
balt = extractData(baltimore)
bost = extractData(boston)
sea = extractData(seattle)
wash = extractData(washington)
den = extractData(denver)
mil = extractData(milwaukee)
#por = extractData(portland)
vegas = extractData(las_vegas)

In [104]:
#function made to make a data frame for each city. Passed in the city data and the name of the city

def createDf (data, city):
    df = pd.DataFrame({'city': city, 'neighborhoods': data[0], 'investment_properties': data[1], 'airbnb_listings': data[2], 'traditional_listings': data[3], 
                       'avg_property_price': data[4],'avg_price_per_sqft': data[5], 'avg_days_on_market': data[6], 'avg_occupancy': data[7],
                      'avg_nightly_price': data[8], 'avg_airbnb_roi': data[9], 'avg_airbnb_rental': data[10], 'avg_traditional_roi': data[11],
                      'avg_traditional_rental': data[12]}, index = [0])
    return df

In [106]:
#creating a data frame for each city, and setting the index

yorkDf = createDf(york, 'New York City').set_index('city')
laDf = createDf(la, 'Los Angeles').set_index('city')
houstDf = createDf(houst, 'Houston').set_index('city')
philDf = createDf(phil, 'Philadelphia').set_index('city')
phoeDf = createDf(phoe, 'Phoenix').set_index('city')
sanDf = createDf(san, 'San Antonio').set_index('city')
sanDDf = createDf(sanD, 'San Diego').set_index('city')
dalDf = createDf(dal, 'Dallas').set_index('city')
sanJDf = createDf(sanJ, 'San Jose').set_index('city')
indDf = createDf(ind, 'Indianapolis').set_index('city')
jackDf = createDf(jack, 'Jacksonville').set_index('city')
sanFDf = createDf(sanF, 'San Francisco').set_index('city')
austDf = createDf(aust, 'Austin').set_index('city')
colDf = createDf(col, 'Columbus').set_index('city')
fortDf = createDf(fort, 'Fort Worth').set_index('city')
louDf = createDf(lou, 'Louisville').set_index('city')
charDf = createDf(char, 'Charlotte').set_index('city')
detDf = createDf(det, 'Detroit').set_index('city')
elDf = createDf(el, 'El Paso').set_index('city')
memDf = createDf(mem, 'Memphis').set_index('city')
nashDf = createDf(nash, 'Nashville').set_index('city')
baltDf = createDf(balt, 'Baltimore').set_index('city')
bostDf = createDf(bost, 'Boston').set_index('city')
seaDf = createDf(sea, 'Seattle').set_index('city')
washDf = createDf(wash, 'Washington D.C').set_index('city')
denDf = createDf(den, 'Denver').set_index('city')
milDf = createDf(mil, 'Milwaukee').set_index('city')
vegasDf = createDf(vegas, 'Las Vegas').set_index('city')

In [107]:
#making sure the data is loaded in correctly

cities = pd.concat([yorkDf, laDf, houstDf, philDf, phoeDf, sanDf, sanDDf, dalDf, sanJDf, indDf, jackDf, sanFDf, austDf, colDf, fortDf, louDf, charDf, 
                    detDf, elDf, memDf, nashDf, baltDf, bostDf, seaDf, washDf, denDf, milDf, vegasDf], axis = 0)
cities

,neighborhoods,investment_properties,airbnb_listings,traditional_listings,avg_property_price,avg_price_per_sqft,avg_days_on_market,avg_occupancy,avg_nightly_price,avg_airbnb_roi,avg_airbnb_rental,avg_traditional_roi,avg_traditional_rental
city,,,,,,,,,,,,,
New York City,266,6252,5722,627,1.107550e+06,680.887865,181.5501,55.7123,164.4086,0.066282,2577.560868,0.834655,2845.543896
Los Angeles,96,3883,4988,743,1.078306e+06,611.890081,82.0972,63.1999,176.2772,1.317489,3944.325154,1.521531,3857.146496
Houston,88,1295,2007,34,4.299116e+05,179.371108,82.4813,47.6564,105.0086,1.061400,2115.948140,1.811595,1988.954066
Philadelphia,158,2321,1859,263,3.396056e+05,338.130722,99.3315,49.5956,119.7097,2.595837,1936.494029,2.340553,1518.753439
Phoenix,15,2621,440,99,4.187390e+05,210.721446,55.6298,62.4674,166.0022,3.514610,2707.832995,2.265723,1868.158108
San Antonio,375,2758,1596,22,2.932870e+05,140.619611,84.5238,48.6411,118.4198,2.211114,2145.054087,1.398267,1638.130625
San Diego,122,1388,2549,59,8.094683e+05,518.510213,53.6736,55.9832,190.8563,1.711617,3235.538433,1.863603,3187.164404
Dallas,32,3291,1299,97,4.116594e+05,204.063471,63.5784,51.1612,125.0361,2.230294,2656.409072,1.023135,1905.019412
San Jose,18,310,400,6,1.081207e+06,677.950238,68.5556,54.5220,191.2506,0.347493,3053.132356,1.185276,3672.416488
Indianapolis,85,1599,752,30,2.591177e+05,122.847842,86.5989,47.6903,147.8592,3.477246,1872.399831,2.366823,1248.743602
Jacksonville,197,2353,745,98,2.642726e+05,142.223156,85.3954,55.3737,119.8668,4.730820,2305.594631,2.391376,1448.138542
San Francisco,89,342,1685,13,1.695222e+06,1136.679510,77.5252,66.5515,229.9755,0.596703,5095.541349,0.419515,4340.456201
Austin,65,558,2062,18,6.291747e+05,311.639122,75.1087,52.2511,194.8927,2.455330,3619.943023,0.433974,1963.204733
Columbus,271,959,866,46,2.572903e+05,149.301932,57.0407,52.8839,114.4970,3.016133,1912.210534,1.765452,1269.990807
Fort Worth,223,3132,587,64,2.963323e+05,140.726461,45.8889,54.6535,134.5572,4.315124,2900.478966,1.672154,1729.830149
Louisville,71,1158,936,25,2.592673e+05,131.049912,69.6285,50.1906,181.4181,5.524629,2410.953222,1.954062,1175.222439
Charlotte,173,1847,1119,18,4.164897e+05,202.540465,71.4304,52.5422,121.2623,1.673080,2055.183351,1.416158,1644.015098
Detroit,92,513,565,41,1.588263e+05,100.466794,118.5098,46.2181,130.7808,4.612995,1675.925052,4.067803,1083.587410
El Paso,55,1539,355,15,2.236135e+05,113.952894,111.9935,61.6723,71.7572,2.836801,1971.445832,1.022319,1279.441079
Memphis,13,589,435,37,2.438737e+05,130.086165,63.5493,51.7103,120.3149,6.969005,2155.001472,2.346604,1149.821353
Nashville,228,1217,2758,30,4.706869e+05,5617.930220,54.8000,44.0326,229.5785,2.741353,2474.609116,1.975052,1889.123653
Baltimore,276,2302,707,90,2.662416e+05,169.990938,99.7015,49.5224,112.5813,10.828930,2006.466802,16.304225,1664.114753
Boston,29,118,866,13,1.034751e+06,718.296529,63.8729,58.9931,213.7158,1.126627,3715.233660,1.015420,3075.666252
Seattle,107,121,1621,2,7.837825e+05,518.324064,53.5250,56.6000,153.3276,0.642299,2338.815902,1.524411,2697.750000
Washington D.C,135,1101,2549,97,7.197712e+05,521.849806,76.0473,60.4067,141.3369,1.156872,2556.089921,1.802804,2601.400790
Denver,78,142,1358,4,5.135251e+05,349.515834,36.2900,63.3840,163.4523,1.929544,2637.867400,1.804805,1990.176056
Milwaukee,188,343,589,15,1.983733e+05,129.740173,59.1217,44.3615,135.0614,2.523979,1595.182916,1.857511,1179.825786
Las Vegas,31,5291,991,33,4.027176e+05,210.720942,81.9240,52.0067,186.5063,4.107545,2514.333601,1.733720,1453.116543

In [110]:
#exporting to csv, in order to load into R

cities.to_csv('real_estate_data.csv')